package org.ssaad.ami.pipeline.common.types

enum TaskType {

    INIT_PIPELINE,
    INIT_CONFIG,
    CODE_BUILD,
    UNIT_TESTING,
    QUALITY_SCANNING,
    DEPENDENCY_CHECK,
    BINARIES_ARCHIVE,
    CONTAINER_BUILD,
    DEPLOY_DEV,
    SYSTEM_TESTING,
    DEPLOY_QA,
    LOAD_TESTING,
    DEPLOY_PROD_LF,
    DEPLOY_PROD_T5,
}
